<?php
$title = 'Editar categoria';
$this->headTitle($title);
?>
    <h2><?php echo $this->escapeHtml($title); ?></h2>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('livraria-admin-interna', [
    'controller' => 'categorias',
    'action' => 'edit'
]));
$form->prepare();
?>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->form($form);?>
    </div>
</div>
