<div class="container">
    <div class="row">
        <h2>Categorias</h2>
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Nome</th>
                <th>Livros</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->categorias as $categoria) : ?>
                <tr>
                    <td><?php echo $categoria->getNome(); ?></td>
                    <td>
                        <?php foreach ($categoria->getLivros() as $livro) : ?>
                            <?php echo $livro->getNome(); ?>
                        <?php endforeach; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
